"""
Log Analysis Pipeline with Drain3 Template Mining 

This module provides production-grade log analysis using Drain3 for template extraction.

MAIN ENTRY POINT:
    analyze_logs(file_path, output_dir, config_path) -> Dict
    
    Returns a JSON-serializable response with:
    - Generated template files (rare_errors, highfreq_errors, warnings, etc.)
    - Template and line counts
    - Pareto-based error frequency analysis

FEATURES:
    - Log level classification (Error, Warning, Info, Unknown)
    - Configuration change detection
    - Error template frequency analysis (Pareto/80-20 rule)
    - Template shifting (errors found in W/I/U → Error category)
    - Configurable output via log_config.json

PROCESSING MODES:
    - ENTIRE FILE: For smaller files (< threshold)
    - CHUNK PIPELINE: For larger files, with parallel/sequential options

CONFIGURATION:
    All settings controlled via log_config.json:
    - output_flags: Control which files to generate
    - frequency_settings: Pareto threshold, sample counts
    - drain3_settings: Template mining parameters
    - preprocessing: Timestamp removal patterns

Usage:
    from testing_log import analyze_logs
    result = analyze_logs("app.log")
    print(result['files'])  # Generated output files
"""

import os
import re
import json
import time
import multiprocessing
from pathlib import Path
from typing import List, Dict, Tuple, Optional, Generator
from collections import defaultdict
from datetime import datetime
from dataclasses import dataclass, field
from concurrent.futures import ProcessPoolExecutor

try:
    from drain3 import TemplateMiner
    from drain3.template_miner_config import TemplateMinerConfig
    DRAIN3_AVAILABLE = True
except ImportError:
    DRAIN3_AVAILABLE = False


# =============================================================================
# CONFIGURATION
# =============================================================================
CONFIG_FILE_NAME = "log_config.json"


@dataclass
class Drain3Config:
    """Drain3 algorithm settings."""
    batch_size: int = 1000
    similarity_threshold: float = 0.3
    depth: int = 4
    max_children: int = 100


@dataclass
class FrequencyConfig:
    """Configuration for template frequency-based segregation (Pareto/80-20 rule).
    
    High-frequency templates: Templates that cumulatively cover X% of total error lines.
    These are typically repetitive/known issues - show only 1 sample per template.
    
    Rare/Priority templates: Templates that fall outside the high-frequency threshold.
    These are priority for investigation - show full detail with all lines.
    
    Note: All output files now include ALL log lines for each template (no sampling).
    """
    # Pareto threshold: templates covering this % of lines are "high frequency"
    # Used as FALLBACK when rare_max_lines_per_template is None.
    high_freq_cumulative_threshold: float = 0.80  # 80% = Pareto rule
    
    # Enable tiered output for errors (creates separate files for high-freq vs rare)
    enable_tiered_error_output: bool = True
    
    # Optional: absolute maximum size for a template to be considered "rare"
    # If set, templates with size <= this value are always considered rare
    # regardless of cumulative threshold. None = disabled.
    rare_absolute_max_size: Optional[int] = None

    # Simple count-based bifurcation: templates with <= this many lines are "rare errors",
    # templates with > this many lines are "high-frequency errors".
    # When set (not None), this OVERRIDES the Pareto cumulative threshold.
    # Default: 15. Set to None to fall back to Pareto threshold.
    rare_max_lines_per_template: Optional[int] = 15


@dataclass
class OutputFlagsConfig:
    """Configuration for controlling which outputs to generate.
    
    These flags control the output files generated by analyze_logs().
    All flags default to True (generate all outputs).
    """
    include_rare_errors: bool = True      # Rare/priority error templates (detailed)
    include_highfreq_errors: bool = True  # High-frequency error templates (summary)
    include_warnings: bool = True         # Warning templates
    include_information: bool = True      # Information templates
    include_unknown: bool = True          # Unknown level templates
    include_config_changes: bool = True   # Configuration change templates


@dataclass
class PreprocessingConfig:
    """Preprocessing settings."""
    remove_timestamps: bool = True
    timestamp_patterns: List[str] = field(default_factory=lambda: [
        r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z?\s*',
        r'^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}(\.\d+)?\s*',
        r'^([IWE])\d{4}\s+\d{2}:\d{2}:\d{2}(\.\d+)?\s*',
        r'^(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}(\.\d+)?\s+\S+\s+',
        r'\b\d{2}:\d{2}:\d{2}(\.\d+)?\b',
    ])


@dataclass
class PipelineConfig:
    """Configuration for the log processing pipeline."""
    # Branch selection
    use_chunk_pipeline: Optional[bool] = None  # None=auto, True=chunk, False=entire
    file_size_threshold_mb: float = 50.0
    
    # Chunk settings
    chunk_size: int = 10_000
    parallel_chunks: bool = True
    chunk_workers: Optional[int] = None
    min_chunks_for_parallel: int = 3
    
    # Output settings
    output_dir: Optional[str] = None
    levels_to_process: List[str] = field(default_factory=lambda: ['E', 'W', 'I', 'UNKNOWN'])
    
    # Sub-configs
    drain3: Drain3Config = field(default_factory=Drain3Config)
    preprocessing: PreprocessingConfig = field(default_factory=PreprocessingConfig)
    frequency: FrequencyConfig = field(default_factory=FrequencyConfig)
    output_flags: OutputFlagsConfig = field(default_factory=OutputFlagsConfig)
    
    # Logging
    verbose: bool = True
    print_progress: bool = True


def load_config(config_path: Optional[str] = None) -> PipelineConfig:
    """
    Load configuration from JSON file.
    
    Search order:
        1. Explicit config_path if provided
        2. log_config.json in current working directory
        3. log_config.json in script directory
        4. Default configuration
    """
    search_paths = []
    
    if config_path:
        search_paths.append(Path(config_path))
    
    # Current working directory
    search_paths.append(Path.cwd() / CONFIG_FILE_NAME)
    
    # Script directory
    search_paths.append(Path(__file__).parent / CONFIG_FILE_NAME)
    
    for path in search_paths:
        if path.exists():
            try:
                with open(path, 'r', encoding='utf-8') as f:
                    config_dict = json.load(f)
                print(f"[Config] Loaded configuration from: {path}")
                
                # Build config from dict
                config = PipelineConfig()
                
                # Pipeline settings
                pipeline = config_dict.get('pipeline', {})
                if 'use_chunk_pipeline' in pipeline:
                    config.use_chunk_pipeline = pipeline['use_chunk_pipeline']
                if 'file_size_threshold_mb' in pipeline:
                    config.file_size_threshold_mb = pipeline['file_size_threshold_mb']
                
                # Chunk settings
                chunk = config_dict.get('chunk_settings', {})
                if 'chunk_size' in chunk:
                    config.chunk_size = chunk['chunk_size']
                if 'parallel_chunks' in chunk:
                    config.parallel_chunks = chunk['parallel_chunks']
                if 'chunk_workers' in chunk:
                    config.chunk_workers = chunk['chunk_workers']
                if 'min_chunks_for_parallel' in chunk:
                    config.min_chunks_for_parallel = chunk['min_chunks_for_parallel']
                
                # Drain3 settings
                drain3 = config_dict.get('drain3_settings', {})
                if 'batch_size' in drain3:
                    config.drain3.batch_size = drain3['batch_size']
                if 'similarity_threshold' in drain3:
                    config.drain3.similarity_threshold = drain3['similarity_threshold']
                if 'depth' in drain3:
                    config.drain3.depth = drain3['depth']
                if 'max_children' in drain3:
                    config.drain3.max_children = drain3['max_children']
                
                # Output settings
                output = config_dict.get('output', {})
                if 'output_dir' in output:
                    config.output_dir = output['output_dir']
                if 'levels_to_process' in output:
                    config.levels_to_process = output['levels_to_process']
                
                # Preprocessing settings
                preproc = config_dict.get('preprocessing', {})
                if 'remove_timestamps' in preproc:
                    config.preprocessing.remove_timestamps = preproc['remove_timestamps']
                if 'timestamp_patterns' in preproc:
                    config.preprocessing.timestamp_patterns = preproc['timestamp_patterns']
                
                # Logging settings
                logging_cfg = config_dict.get('logging', {})
                if 'verbose' in logging_cfg:
                    config.verbose = logging_cfg['verbose']
                if 'print_progress' in logging_cfg:
                    config.print_progress = logging_cfg['print_progress']
                
                # Frequency settings (Pareto/80-20 rule for error template classification)
                freq = config_dict.get('frequency_settings', {})
                if 'high_freq_cumulative_threshold' in freq:
                    config.frequency.high_freq_cumulative_threshold = freq['high_freq_cumulative_threshold']
                if 'enable_tiered_error_output' in freq:
                    config.frequency.enable_tiered_error_output = freq['enable_tiered_error_output']
                if 'rare_absolute_max_size' in freq:
                    config.frequency.rare_absolute_max_size = freq['rare_absolute_max_size']
                if 'rare_max_lines_per_template' in freq:
                    config.frequency.rare_max_lines_per_template = freq['rare_max_lines_per_template']
                
                # Output flags (control which outputs to generate)
                output_flags = config_dict.get('output_flags', {})
                if 'include_rare_errors' in output_flags:
                    config.output_flags.include_rare_errors = output_flags['include_rare_errors']
                if 'include_highfreq_errors' in output_flags:
                    config.output_flags.include_highfreq_errors = output_flags['include_highfreq_errors']
                if 'include_warnings' in output_flags:
                    config.output_flags.include_warnings = output_flags['include_warnings']
                if 'include_information' in output_flags:
                    config.output_flags.include_information = output_flags['include_information']
                if 'include_unknown' in output_flags:
                    config.output_flags.include_unknown = output_flags['include_unknown']
                if 'include_config_changes' in output_flags:
                    config.output_flags.include_config_changes = output_flags['include_config_changes']
                
                return config
                
            except (json.JSONDecodeError, Exception) as e:
                print(f"[Config] Warning: Error loading {path}: {e}")
                continue
    
    print("[Config] Using default configuration")
    return PipelineConfig()


# Global config instance (loaded on first use)
_GLOBAL_CONFIG: Optional[PipelineConfig] = None


def get_config(config_path: Optional[str] = None, reload: bool = False) -> PipelineConfig:
    """Get the global configuration instance."""
    global _GLOBAL_CONFIG
    if _GLOBAL_CONFIG is None or reload:
        _GLOBAL_CONFIG = load_config(config_path)
    return _GLOBAL_CONFIG


# Default configuration (for backward compatibility)
DEFAULT_CONFIG = PipelineConfig()


# =============================================================================
# TIMESTAMP PARSER
# =============================================================================
def remove_timestamps(log_line: str, config: Optional[PipelineConfig] = None) -> str:
    """
    Remove timestamp entries from a single log line.
    
    Uses patterns from config.preprocessing.timestamp_patterns if provided,
    otherwise uses default hardcoded patterns.
    """
    if not log_line.strip():
        return log_line
    
    config = config or get_config()
    
    # Check if timestamp removal is enabled
    if not config.preprocessing.remove_timestamps:
        return log_line
    
    line = log_line
    
    # Use configurable patterns
    patterns = config.preprocessing.timestamp_patterns
    
    # Apply each pattern
    for i, pattern in enumerate(patterns):
        # Pattern at index 2 is the I/W/E + MMDD pattern, needs special replacement
        if i == 2 and pattern.startswith('^([IWE])'):
            line = re.sub(pattern, r'\1 ', line)
        # Pattern at index 3 is systemd/journal, needs case-insensitive
        elif i == 3 and 'Jan|Feb|Mar' in pattern:
            line = re.sub(pattern, '', line, flags=re.IGNORECASE)
        else:
            line = re.sub(pattern, '', line)
    
    # Clean up whitespace
    line = re.sub(r'\s+', ' ', line).strip()
    return line


# =============================================================================
# TIMESTAMP EXTRACTION FROM LOG LINES (for sampling by time)
# =============================================================================

# Month abbreviation -> number mapping for systemd/journal timestamps
_MONTH_MAP = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12,
}

# Pattern: Jan 12 14:22:56 (systemd/journal logs)
_TS_SYSTEMD = re.compile(
    r'^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{1,2})\s+(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?'
)

# Pattern: I0112 14:22:56 or E0112 14:22:56 (Kubernetes logs)
# Format is: <level><MMDD> <HH:MM:SS>  — e.g. I0112 means Info, Jan 12
_TS_KUBE = re.compile(
    r'^[IWEU](\d{4})\s+(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?'
)

# Pattern: 2024-01-12T14:22:56 (ISO timestamps)
_TS_ISO = re.compile(
    r'(\d{4})-(\d{2})-(\d{2})[T\s](\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?'
)


def extract_timestamp_from_log(log_line: str) -> Optional[str]:
    """
    Extract a sortable timestamp string from a log line.

    Supported formats (checked in order):
        1. ``Jan 12 14:22:56``  – systemd / journal logs
        2. ``I0112 14:22:56``   – Kubernetes I/W/E/U prefixed logs
        3. ``2024-01-12T14:22:56`` – ISO 8601 timestamps

    Returns:
        A sortable string in the form ``MMDD-HH:MM:SS.ffffff`` (for formats 1 & 2)
        or ``YYYY-MM-DDTHH:MM:SS.ffffff`` (for ISO), or ``None`` if no timestamp
        could be parsed.  The returned string is designed for lexicographic
        ordering so that ``sorted()`` produces chronological order.
    """
    if not log_line:
        return None

    # 1. Systemd / journal:  Jan 12 14:22:56.123456
    m = _TS_SYSTEMD.match(log_line)
    if m:
        month = _MONTH_MAP.get(m.group(1), 0)
        day = int(m.group(2))
        frac = (m.group(6) or '0').ljust(6, '0')[:6]
        return f"{month:02d}{day:02d}-{m.group(3)}:{m.group(4)}:{m.group(5)}.{frac}"

    # 2. Kubernetes:  E0112 14:22:56.789
    m = _TS_KUBE.match(log_line)
    if m:
        mmdd = m.group(1)  # "MMDD" — 4 digits captured after the level char (e.g. "0112" = Jan 12)
        frac = (m.group(5) or '0').ljust(6, '0')[:6]
        return f"{mmdd}-{m.group(2)}:{m.group(3)}:{m.group(4)}.{frac}"

    # 3. ISO 8601:  2024-01-12T14:22:56.123Z
    m = _TS_ISO.search(log_line)
    if m:
        frac = (m.group(7) or '0').ljust(6, '0')[:6]
        return (f"{m.group(1)}-{m.group(2)}-{m.group(3)}T"
                f"{m.group(4)}:{m.group(5)}:{m.group(6)}.{frac}")

    return None


def sample_lines_by_timestamp(
    lines: List[str],
    first_n: int = 3,
    middle_n: int = 1,
    last_n: int = 3,
) -> List[str]:
    """
    Sample representative lines from a list using timestamp-based ordering.

    For a template cluster with many lines this returns a small, representative
    subset that shows *when the error started* (first N), a *mid-point*
    occurrence (middle N), and the *most recent* occurrences (last N).

    Algorithm:
        1. Try to parse a timestamp from each line via
           :func:`extract_timestamp_from_log`.
        2. If **any** timestamps were found, sort lines by timestamp.
           Otherwise, keep original order (log files are usually
           chronologically ordered).
        3. Sample ``first_n + middle_n + last_n`` lines (default 7).
        4. If the cluster has fewer lines than the sample size, return all
           lines (no sampling needed).

    Args:
        lines:    All original log lines belonging to one template cluster.
        first_n:  Number of earliest lines to include  (default 3).
        middle_n: Number of middle lines to include     (default 1).
        last_n:   Number of latest lines to include     (default 3).

    Returns:
        A list of sampled original log lines (order preserved from the
        sorted/original sequence).
    """
    total_sample = first_n + middle_n + last_n  # default 7

    if len(lines) <= total_sample:
        return list(lines)  # nothing to sample — return all

    # Attempt timestamp extraction
    ts_line_pairs = []
    has_timestamps = False
    for line in lines:
        ts = extract_timestamp_from_log(line)
        ts_line_pairs.append((ts, line))
        if ts is not None:
            has_timestamps = True

    # Sort by timestamp if available; otherwise keep original order
    if has_timestamps:
        # Lines without a timestamp get a sentinel that sorts first
        ts_line_pairs.sort(key=lambda pair: pair[0] if pair[0] is not None else '')

    sorted_lines = [line for _, line in ts_line_pairs]

    # Sample indices
    n = len(sorted_lines)
    first_indices = list(range(0, min(first_n, n)))
    last_indices = list(range(max(n - last_n, 0), n))
    mid_start = (n // 2) - (middle_n // 2)
    middle_indices = list(range(mid_start, min(mid_start + middle_n, n)))

    # Merge indices, deduplicate, preserve order
    seen = set()
    sampled = []
    for idx in first_indices + middle_indices + last_indices:
        if idx not in seen:
            seen.add(idx)
            sampled.append(sorted_lines[idx])

    return sampled


# =============================================================================
# LOG LEVEL PARSER
# =============================================================================
def parse_log_level(log_line: str) -> Optional[str]:
    """
    Parse log level from a log line.
    
    Prioritizes content-based detection (error/warning phrases)
    over structural prefixes (I/W/E) because Info-level logs often contain errors.
    
    Returns:
        'E' for Error, 'W' for Warning, 'I' for Info, None for Unknown
    """
    if not log_line.strip():
        return None
    s = log_line.strip()
    upper = s.upper()
    
    # 1) Content-based detection: Error phrases (highest priority)
    error_phrases = [
        r'\bFAILURE\b', r'\bFAILED\b', r'\bstatus=1/', r'\bstatus=2/', r'\bstatus=3/',
        r"exit-code", r"exit code", r"exited with", r"exited, code=",
        r"failed to start", r"could not start", r"failed with result",
        r'\bERROR\b', r'\bFATAL\b', r'\bCRASH', r'\bOOMKILLED\b',
        r'\bTIMEOUT\b', r'\bUNREACHABLE\b', r'\bREFUSED\b',
        r'connection refused', r'no such file', r'permission denied',
    ]
    for pat in error_phrases:
        if re.search(pat, upper):
            return 'E'
    
    # 2) Content-based detection: Warning phrases
    warn_phrases = [r'\bWARN(?:ING)?\b', r'\bDEPRECATED\b', r'\bRETRY\b', r'\bBACKOFF\b']
    for pat in warn_phrases:
        if re.search(pat, upper):
            return 'W'
    
    # 3) Structural prefix: I/W/E at start of line (Kubernetes-style logs)
    #    Handles both original (E0112, W0112, I0112) and preprocessed (E , W , I ) formats
    #    After timestamp removal, "W0112 17:02:33..." becomes "W ..."
    match = re.match(r'([IWEiwe])(?:\d{4}\b|\s)', s)
    if match:
        return match.group(1).upper()
    
    # 4) Bracketed level [INFO], [WARN], [ERROR]
    match = re.search(r'\[(INFO|WARN|WARNING|ERROR|ERR)\]', upper)
    if match:
        level_str = match.group(1)
        if level_str in ['INFO', 'INFORMATION']:
            return 'I'
        elif level_str in ['WARN', 'WARNING']:
            return 'W'
        elif level_str in ['ERROR', 'ERR']:
            return 'E'
    
    # 5) Info keywords
    if re.search(r'\bINFO\b', upper) or re.search(r'\bStarted\b', s):
        return 'I'
    
    return None


# =============================================================================
# DRAIN3 UTILITIES
# =============================================================================
def create_drain3_miner(config: Optional[PipelineConfig] = None) -> 'TemplateMiner':
    """Create and configure a new Drain3 TemplateMiner instance."""
    config = config or get_config()
    drain_config = TemplateMinerConfig()
    drain_config.sim_th = config.drain3.similarity_threshold
    drain_config.depth = config.drain3.depth
    drain_config.max_children = config.drain3.max_children
    drain_config.profiling_enabled = False
    return TemplateMiner(config=drain_config)


def extract_drain3_results(miner: 'TemplateMiner') -> Tuple[Dict, List[Dict]]:
    """Extract cluster sizes and template list from a Drain3 miner."""
    cluster_sizes = {}
    template_list = []
    
    clusters = miner.drain.clusters if hasattr(miner, 'drain') else []
    
    # Handle both list and dict formats
    if isinstance(clusters, dict):
        cluster_list = list(clusters.values())
    elif hasattr(clusters, '__iter__'):
        cluster_list = list(clusters)
    else:
        cluster_list = []
    
    for cluster in cluster_list:
        try:
            # Use the ACTUAL cluster_id from the LogCluster object
            # This ensures consistency with miner.match() results
            cid = getattr(cluster, 'cluster_id', None)
            if cid is None:
                continue
            size = getattr(cluster, 'size', 1)
            template = cluster.get_template() if hasattr(cluster, 'get_template') else str(cluster)
            cluster_sizes[cid] = size
            template_list.append({'id': cid, 'template': template, 'size': size})
        except Exception:
            pass
    
    return cluster_sizes, template_list


def process_lines_with_drain3(
    lines: List[str],
    config: Optional[PipelineConfig] = None
) -> Tuple[Dict, List[Dict], List]:
    """Process lines through Drain3 in batches.
    
    Returns:
        Tuple of (cluster_sizes, template_list, event_ids)
        - event_ids: List of FINAL cluster_ids for each input line
    """
    if not DRAIN3_AVAILABLE or not lines:
        return {}, [], [None] * len(lines)
    
    config = config or get_config()
    batch_size = config.drain3.batch_size
    
    miner = create_drain3_miner(config)
    
    # STEP 1: Process all lines to build the clusters
    for i in range(0, len(lines), batch_size):
        batch = lines[i:i + batch_size]
        for line in batch:
            if line.strip():
                miner.add_log_message(line)
    
    # STEP 2: Extract final cluster results
    cluster_sizes, template_list = extract_drain3_results(miner)
    
    # STEP 3: Re-match each line to its FINAL cluster ID
    # This ensures event_ids reflect the final cluster assignments
    event_ids = []
    for line in lines:
        if line.strip():
            # match() returns the cluster without modifying the miner
            result = miner.match(line)
            if result:
                event_ids.append(result.cluster_id)
            else:
                event_ids.append(None)
        else:
            event_ids.append(None)
    
    return cluster_sizes, template_list, event_ids




# =============================================================================
# BRANCH 1: ENTIRE FILE PIPELINE
# =============================================================================
def entire_file_pipeline(file_path: str, config: Optional[PipelineConfig] = None) -> Dict[str, Dict[str, List[str]]]:
    """
    BRANCH 1: Process entire file at once.
    
    Pipeline:
        1. Read entire file into memory
        2. Process all lines through timestamp parser
        3. Categorize all lines by log level
    
    Best for: Smaller files (< file_size_threshold_mb)
    
    Args:
        file_path: Path to the log file
        config: Pipeline configuration (uses global config if None)
    
    Returns:
        Dict mapping level ('E', 'W', 'I', 'UNKNOWN') to
        {"preprocessed": [lines], "original": [lines]}
    """
    config = config or get_config()
    
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            log_content = f.read()
    except Exception as e:
        if config.verbose:
            print(f"[EntireFile] Error reading file {file_path}: {e}")
        return {}
    
    if not log_content.strip():
        return {}
    
    result = defaultdict(lambda: {"preprocessed": [], "original": []})
    for line in log_content.split('\n'):
        if not line.strip():
            continue
        # Step 1: Remove timestamps (using config)
        preprocessed_line = remove_timestamps(line, config)
        # Step 2: Categorize by log level (using config)
        level = parse_log_level(preprocessed_line)
        if level == 'E':
            result['E']["preprocessed"].append(preprocessed_line)
            result['E']["original"].append(line)
        elif level == 'W':
            result['W']["preprocessed"].append(preprocessed_line)
            result['W']["original"].append(line)
        elif level == 'I':
            result['I']["preprocessed"].append(preprocessed_line)
            result['I']["original"].append(line)
        else:
            result['UNKNOWN']["preprocessed"].append(preprocessed_line)
            result['UNKNOWN']["original"].append(line)
    
    return dict(result)


# =============================================================================
# BRANCH 2: CHUNK PIPELINE - Core Functions
# =============================================================================
def chunk_file_reader(file_path: str, chunk_size: int) -> Generator[List[str], None, None]:
    """
    Generator that reads a file in chunks.
    
    Yields:
        List[str]: A chunk of lines (up to chunk_size lines per chunk)
    """
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            chunk = []
            for line in f:
                stripped = line.rstrip('\n\r')
                if stripped:
                    chunk.append(stripped)
                    if len(chunk) >= chunk_size:
                        yield chunk
                        chunk = []
            if chunk:
                yield chunk
    except Exception as e:
        print(f"[ChunkReader] Error reading file {file_path}: {e}")


def process_single_chunk(chunk: List[str], config: Optional[PipelineConfig] = None) -> Dict[str, Dict[str, List[str]]]:
    """
    Process a single chunk: timestamp removal + categorization.
    
    This function is the worker for both sequential and parallel processing.
    
    Args:
        chunk: List of raw log lines
        config: Pipeline configuration (uses global config if None)
    
    Returns:
        Dict mapping level ('E', 'W', 'I', 'UNKNOWN') to
        {"preprocessed": [lines], "original": [lines]}
    """
    config = config or get_config()
    categorized = defaultdict(lambda: {"preprocessed": [], "original": []})
    
    for line in chunk:
        # Step 1: Remove timestamps (using config)
        preprocessed = remove_timestamps(line, config)
        # Step 2: Categorize by log level (using config)
        level = parse_log_level(preprocessed)
        if level == 'E':
            categorized['E']["preprocessed"].append(preprocessed)
            categorized['E']["original"].append(line)
        elif level == 'W':
            categorized['W']["preprocessed"].append(preprocessed)
            categorized['W']["original"].append(line)
        elif level == 'I':
            categorized['I']["preprocessed"].append(preprocessed)
            categorized['I']["original"].append(line)
        else:
            categorized['UNKNOWN']["preprocessed"].append(preprocessed)
            categorized['UNKNOWN']["original"].append(line)
    
    return dict(categorized)


def merge_chunk_results(results: List[Dict[str, Dict[str, List[str]]]]) -> Dict[str, Dict[str, List[str]]]:
    """Merge categorized results from multiple chunks."""
    merged = defaultdict(lambda: {"preprocessed": [], "original": []})
    for result in results:
        for level, data in result.items():
            if isinstance(data, dict) and "preprocessed" in data:
                merged[level]["preprocessed"].extend(data["preprocessed"])
                merged[level]["original"].extend(data["original"])
            elif isinstance(data, list):
                # Backward compat: old format without originals
                merged[level]["preprocessed"].extend(data)
                merged[level]["original"].extend(data)
    return dict(merged)


# =============================================================================
# BRANCH 2A: CHUNK PIPELINE - SEQUENTIAL
# =============================================================================
def chunk_pipeline_sequential(file_path: str, config: Optional[PipelineConfig] = None) -> Dict[str, List[str]]:
    """
    BRANCH 2A: Process file in chunks SEQUENTIALLY.
    
    Pipeline:
        1. Read file chunk by chunk
        2. For each chunk:
           - Remove timestamps
           - Categorize by log level
        3. Accumulate results
    
    Args:
        file_path: Path to the log file
        config: Pipeline configuration (uses global config if None)
    
    Returns:
        Dict mapping level ('E', 'W', 'I', 'UNKNOWN') to list of preprocessed lines
    """
    config = config or get_config()
    by_level = defaultdict(list)
    chunk_count = 0
    
    for chunk in chunk_file_reader(file_path, config.chunk_size):
        chunk_count += 1
        # Process this chunk (passing config)
        chunk_result = process_single_chunk(chunk, config)
        # Accumulate results
        for level, lines in chunk_result.items():
            by_level[level].extend(lines)
    
    return dict(by_level)


# =============================================================================
# BRANCH 2B: CHUNK PIPELINE - PARALLEL
# =============================================================================
def chunk_pipeline_parallel(file_path: str, config: Optional[PipelineConfig] = None) -> Dict[str, List[str]]:
    """
    BRANCH 2B: Process file chunks IN PARALLEL using multiprocessing.
    
    Pipeline:
        1. Read all chunks from file (sequential I/O)
        2. Process chunks in parallel (timestamp + categorization)
        3. Merge results from all chunks
    
    Note: For parallel processing, config is loaded fresh in each worker process.
    
    Args:
        file_path: Path to the log file
        config: Pipeline configuration (uses global config if None)
    
    Returns:
        Dict mapping level ('E', 'W', 'I', 'UNKNOWN') to list of preprocessed lines
    """
    config = config or get_config()
    
    # Step 1: Read all chunks into memory (I/O is sequential)
    chunks = list(chunk_file_reader(file_path, config.chunk_size))
    
    if not chunks:
        return {}
    
    num_chunks = len(chunks)
    
    # Check if parallel is worth it
    if num_chunks < config.min_chunks_for_parallel:
        # Fall back to sequential for small number of chunks
        return chunk_pipeline_sequential(file_path, config)
    
    # Determine worker count
    max_workers = config.chunk_workers
    if max_workers is None:
        max_workers = min(multiprocessing.cpu_count(), num_chunks, 8)
    
    # Step 2: Process chunks in parallel
    chunk_results = []
    
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(process_single_chunk, chunk) for chunk in chunks]
        
        # Collect results (preserves order)
        for future in futures:
            try:
                result = future.result()
                chunk_results.append(result)
            except Exception as e:
                print(f"[ChunkParallel] Error processing chunk: {e}")
    
    # Step 3: Merge all chunk results
    return merge_chunk_results(chunk_results)


# =============================================================================
# UNIFIED CHUNK PIPELINE (auto-selects sequential or parallel)
# =============================================================================
def chunk_pipeline(file_path: str, config: Optional[PipelineConfig] = None) -> Dict[str, List[str]]:
    """
    BRANCH 2: Process file in chunks.
    
    Automatically selects SEQUENTIAL or PARALLEL mode based on config.parallel_chunks.
    
    Args:
        file_path: Path to the log file
        config: Pipeline configuration (uses global config if None)
    
    Returns:
        Dict mapping level ('E', 'W', 'I', 'UNKNOWN') to list of preprocessed lines
    """
    config = config or get_config()
    if config.parallel_chunks:
        return chunk_pipeline_parallel(file_path, config)
    else:
        return chunk_pipeline_sequential(file_path, config)


def build_cluster_to_lines(
    lines: List[str],
    event_ids: List,
) -> Dict[int, List[str]]:
    """Map cluster_id -> list of original log lines that belong to that cluster."""
    cluster_to_lines: Dict[int, List[str]] = defaultdict(list)
    for i, line in enumerate(lines):
        if i >= len(event_ids):
            break
        cid = event_ids[i]
        if cid is not None:
            cluster_to_lines[cid].append(line)
    return dict(cluster_to_lines)


# =============================================================================
# SAVE LOG LINES
# =============================================================================
def save_templates_to_file(
    template_list: List[Dict],
    cluster_sizes: Dict,
    logs: List[Tuple[str, str]],
    event_ids: List,
    output_dir: str,
    level_suffix: str,
    filename_prefix: Optional[str] = None,
    cluster_to_lines: Optional[Dict[int, List[str]]] = None,
    max_original_lines_per_cluster: int = 5000,
) -> str:
    """
    Save the log lines for one level to a file (no templates/headers).
    Also saves a companion template file listing each Drain3 template
    with its cluster size, named ``<filename_prefix>_<level_suffix>_templates.txt``.
    
    Args:
        template_list: List of template dicts
        cluster_sizes: Dict of cluster_id -> size
        logs: List of (file_path, line) tuples
        event_ids: Event IDs from Drain3
        output_dir: Output directory
        level_suffix: Level name (e.g., 'Warning', 'Information')
        filename_prefix: Optional filename prefix
        cluster_to_lines: Mapping of cluster_id -> original lines
        max_original_lines_per_cluster: Ignored
    
    Returns:
        Path to saved log-lines file
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    if filename_prefix:
        filename = output_path / f"{filename_prefix}_{level_suffix}.txt"
        template_filename = output_path / f"{filename_prefix}_{level_suffix}_templates.txt"
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = output_path / f"log_classification_{level_suffix}_{timestamp}.txt"
        template_filename = output_path / f"log_classification_{level_suffix}_templates_{timestamp}.txt"
    
    cluster_to_lines = cluster_to_lines or {}
    
    # Collect all log lines from all clusters
    all_lines = []
    for tmpl in template_list:
        cid = tmpl['id']
        lines = cluster_to_lines.get(cid, [])
        all_lines.extend(lines)
    
    # Write only the log lines
    with open(filename, 'w', encoding='utf-8') as f:
        for line in all_lines:
            f.write(line + "\n")

    # ── Save companion template file ──
    if template_list:
        with open(template_filename, 'w', encoding='utf-8') as f:
            f.write(f"# {level_suffix} Templates ({len(template_list)} templates)\n")
            f.write(f"# Each template shown with cluster size (number of matching log lines)\n")
            f.write("=" * 80 + "\n\n")
            for i, tmpl in enumerate(template_list, 1):
                cid = tmpl['id']
                size = cluster_sizes.get(cid, tmpl.get('size', len(cluster_to_lines.get(cid, []))))
                template_text = tmpl.get('template', '(unknown)')
                f.write(f"Template {i}  |  cluster_id={cid}  |  lines={size}\n")
                f.write(f"  {template_text}\n\n")
    
    return str(filename)


# =============================================================================
# CONFIGURATION CHANGE AND ERROR DETECTION
# =============================================================================

# Patterns that indicate configuration changes in OpenShift/Kubernetes logs
CONFIG_CHANGE_PATTERNS = [
    r'ObservedConfigChanged',
    r'OperatorStatusChanged',
    r'OperatorVersionChanged',
    r'FeatureGates\s*(updated|initialized)',
    r'Config\s*Drift\s*Monitor',
    r'currentConfig',
    r'desiredConfig',
    r'ConfigMapCreated',
    r'ConfigMapUpdated',
    r'DeploymentUpdated',
    r'DaemonSetUpdated',
    r'ValidatingWebhookConfigurationUpdated',
    r'MutatingWebhookConfigurationUpdated',
    r'TLSConfigChanged',
    r'Update\s+completed\s+for\s+config',
    r'rendered-master-',
    r'rendered-worker-',
    r'Setting\s+node.*currentConfig',
    r'MachineConfiguration\s+status',
    r'Status\s+for\s+clusteroperator',
    r'version.*changed',
    r'ObserveTLS',
    r'ObserveAPI',
]

# Compiled regex for configuration change detection (case-insensitive)
CONFIG_CHANGE_REGEX = re.compile(
    '|'.join(CONFIG_CHANGE_PATTERNS),
    re.IGNORECASE
)

# Error patterns for detecting errors in non-Error categories
ERROR_DETECTION_PATTERNS = [
    r'\bERROR\b',
    r'\bFAILED\b',
    r'\bFAILURE\b',
    r'\bFATAL\b',
    r'\bCRASH',
    r'\bPANIC\b',
    r'\bOOMKILLED\b',
    r'\bTIMEOUT\b',
    r'Unhandled\s*Error',
    r'reconciliation\s*failed',
    r'connection\s*refused',
    r'no\s*such\s*file',
    r'permission\s*denied',
    r'exit[- ]code[=:\s]+[1-9]',
    r'status[=:\s]+[1-9]',
    r'exited\s+with\s+[1-9]',
]

# Compiled regex for error detection (case-insensitive)
ERROR_DETECTION_REGEX = re.compile(
    '|'.join(ERROR_DETECTION_PATTERNS),
    re.IGNORECASE
)


def is_error_template(template: str) -> bool:
    """Check if a template contains error indicators."""
    return bool(ERROR_DETECTION_REGEX.search(template))


def is_config_change_template(template: str) -> bool:
    """Check if a template represents a configuration change."""
    return bool(CONFIG_CHANGE_REGEX.search(template))


def classify_templates_for_level(
    level: str,
    template_list: List[Dict],
    cluster_to_lines: Dict[int, List[str]],
    lines: List[str],
    event_ids: List,
) -> Dict[str, Dict]:
    """
    Classify templates from a non-Error level into:
    1. Error templates (contain error indicators) -> to be moved to Error
    2. Config change templates -> to be moved to ConfigChanges
    3. Regular templates -> stay in original level
    
    Works at TEMPLATE level - entire clusters (template + all lines) move together.
    
    Args:
        level: Current level ('W', 'I', or 'UNKNOWN')
        template_list: List of Drain3 templates
        cluster_to_lines: Mapping of cluster_id -> original lines
        lines: All lines for this level
        event_ids: Event IDs from Drain3 (cluster assignments)
    
    Returns:
        Dict with keys 'regular', 'error', 'config' each containing:
            - templates: List of template dicts
            - cluster_to_lines: Dict of cluster_id -> lines
            - cluster_ids: Set of cluster IDs
    """
    # Skip classification for Error level
    if level == 'E':
        return {
            'regular': {
                'templates': template_list,
                'cluster_to_lines': cluster_to_lines,
                'cluster_ids': {t['id'] for t in template_list},
            },
            'error': {'templates': [], 'cluster_to_lines': {}, 'cluster_ids': set()},
            'config': {'templates': [], 'cluster_to_lines': {}, 'cluster_ids': set()},
        }
    
    # Classify each template
    regular_templates = []
    error_templates = []
    config_templates = []
    
    regular_cluster_ids = set()
    error_cluster_ids = set()
    config_cluster_ids = set()
    
    for tmpl in template_list:
        template_text = tmpl['template']
        cluster_id = tmpl['id']
        
        # Priority: Error > Config > Regular
        if is_error_template(template_text):
            error_templates.append(tmpl)
            error_cluster_ids.add(cluster_id)
        elif is_config_change_template(template_text):
            config_templates.append(tmpl)
            config_cluster_ids.add(cluster_id)
        else:
            regular_templates.append(tmpl)
            regular_cluster_ids.add(cluster_id)
    
    # Separate cluster_to_lines based on template classification
    regular_cluster_to_lines = {}
    error_cluster_to_lines = {}
    config_cluster_to_lines = {}
    
    for cid, clines in cluster_to_lines.items():
        if cid in error_cluster_ids:
            error_cluster_to_lines[cid] = clines
        elif cid in config_cluster_ids:
            config_cluster_to_lines[cid] = clines
        elif cid in regular_cluster_ids:
            regular_cluster_to_lines[cid] = clines
    
    return {
        'regular': {
            'templates': regular_templates,
            'cluster_to_lines': regular_cluster_to_lines,
            'cluster_ids': regular_cluster_ids,
        },
        'error': {
            'templates': error_templates,
            'cluster_to_lines': error_cluster_to_lines,
            'cluster_ids': error_cluster_ids,
        },
        'config': {
            'templates': config_templates,
            'cluster_to_lines': config_cluster_to_lines,
            'cluster_ids': config_cluster_ids,
        },
    }


def get_lines_for_clusters(
    lines: List[str],
    event_ids: List,
    cluster_ids: set,
) -> Tuple[List[str], List]:
    """Get lines and event_ids that belong to specific clusters."""
    filtered_lines = []
    filtered_event_ids = []
    
    for line, eid in zip(lines, event_ids):
        if eid in cluster_ids:
            filtered_lines.append(line)
            filtered_event_ids.append(eid)
    
    return filtered_lines, filtered_event_ids


def merge_template_results(
    results_list: List[Dict],
) -> Dict:
    """
    Merge multiple template results into one.
    Each result has: templates, cluster_to_lines, cluster_ids
    """
    merged_templates = []
    merged_cluster_to_lines = {}
    merged_cluster_ids = set()
    
    for result in results_list:
        merged_templates.extend(result.get('templates', []))
        merged_cluster_to_lines.update(result.get('cluster_to_lines', {}))
        merged_cluster_ids.update(result.get('cluster_ids', set()))
    
    return {
        'templates': merged_templates,
        'cluster_to_lines': merged_cluster_to_lines,
        'cluster_ids': merged_cluster_ids,
    }


# =============================================================================
# FREQUENCY-BASED TEMPLATE CLASSIFICATION (PARETO/80-20 RULE)
# =============================================================================

def classify_templates_by_frequency(
    template_list: List[Dict],
    cluster_to_lines: Dict[int, List[str]],
    freq_config: FrequencyConfig,
) -> Dict[str, Dict]:
    """
    Classify templates into high-frequency vs rare using Pareto/80-20 rule.
    
    High-frequency: Templates that cumulatively account for X% of total error lines.
                   These are repetitive/known issues - only 1 sample needed.
    
    Rare/Priority: Templates outside the high-frequency threshold.
                  These need full investigation - show all lines.
    
    Algorithm:
        1. Sort templates by size (descending)
        2. Cumulative sum until threshold (e.g., 80%) is reached
        3. Templates in cumulative sum = high frequency
        4. Remaining templates = rare/priority
    
    Args:
        template_list: List of template dicts with 'id', 'size', 'template' keys
        cluster_to_lines: Mapping of cluster_id -> original log lines
        freq_config: Frequency configuration settings
    
    Returns:
        Dict with keys 'high_freq' and 'rare', each containing:
            - templates: List of template dicts (sorted by size desc)
            - cluster_to_lines: Dict of cluster_id -> lines
            - cluster_ids: Set of cluster IDs
            - total_lines: Total line count for this category
            - stats: Additional statistics (percentage coverage, etc.)
    """
    if not template_list:
        empty_result = {
            'templates': [],
            'cluster_to_lines': {},
            'cluster_ids': set(),
            'total_lines': 0,
            'stats': {'template_count': 0, 'line_coverage_pct': 0.0},
        }
        return {'high_freq': empty_result, 'rare': empty_result}
    
    # Sort templates by size (descending) for Pareto analysis
    sorted_templates = sorted(template_list, key=lambda x: x['size'], reverse=True)
    
    # Calculate total lines across all templates
    total_lines = sum(t['size'] for t in sorted_templates)
    
    if total_lines == 0:
        empty_result = {
            'templates': [],
            'cluster_to_lines': {},
            'cluster_ids': set(),
            'total_lines': 0,
            'stats': {'template_count': 0, 'line_coverage_pct': 0.0},
        }
        return {'high_freq': empty_result, 'rare': empty_result}
    
    # Determine bifurcation strategy
    use_count_based = (freq_config.rare_max_lines_per_template is not None)
    count_threshold = freq_config.rare_max_lines_per_template or 15

    high_freq_templates = []
    high_freq_cluster_ids = set()
    rare_templates = []
    rare_cluster_ids = set()

    if use_count_based:
        # ── COUNT-BASED: templates with > N lines = high-freq, <= N = rare ──
        for tmpl in sorted_templates:
            cluster_id = tmpl['id']
            template_size = tmpl['size']

            if template_size > count_threshold:
                high_freq_templates.append(tmpl)
                high_freq_cluster_ids.add(cluster_id)
            else:
                rare_templates.append(tmpl)
                rare_cluster_ids.add(cluster_id)
    else:
        # ── PARETO-BASED (fallback): cumulative coverage threshold ──
        threshold_lines = total_lines * freq_config.high_freq_cumulative_threshold
        cumulative_lines = 0

        for tmpl in sorted_templates:
            cluster_id = tmpl['id']
            template_size = tmpl['size']

            # Check if this template should be forced into "rare" category
            # based on absolute size threshold (if configured)
            if (freq_config.rare_absolute_max_size is not None
                and template_size <= freq_config.rare_absolute_max_size):
                rare_templates.append(tmpl)
                rare_cluster_ids.add(cluster_id)
                continue

            # Pareto classification
            if cumulative_lines < threshold_lines:
                high_freq_templates.append(tmpl)
                high_freq_cluster_ids.add(cluster_id)
                cumulative_lines += template_size
            else:
                rare_templates.append(tmpl)
                rare_cluster_ids.add(cluster_id)
    
    # Split cluster_to_lines based on classification
    high_freq_cluster_to_lines = {
        cid: lines for cid, lines in cluster_to_lines.items()
        if cid in high_freq_cluster_ids
    }
    rare_cluster_to_lines = {
        cid: lines for cid, lines in cluster_to_lines.items()
        if cid in rare_cluster_ids
    }
    
    # Calculate stats
    high_freq_lines = sum(t['size'] for t in high_freq_templates)
    rare_lines = sum(t['size'] for t in rare_templates)
    
    return {
        'high_freq': {
            'templates': high_freq_templates,
            'cluster_to_lines': high_freq_cluster_to_lines,
            'cluster_ids': high_freq_cluster_ids,
            'total_lines': high_freq_lines,
            'stats': {
                'template_count': len(high_freq_templates),
                'line_coverage_pct': (high_freq_lines / total_lines * 100) if total_lines > 0 else 0,
            },
        },
        'rare': {
            'templates': rare_templates,
            'cluster_to_lines': rare_cluster_to_lines,
            'cluster_ids': rare_cluster_ids,
            'total_lines': rare_lines,
            'stats': {
                'template_count': len(rare_templates),
                'line_coverage_pct': (rare_lines / total_lines * 100) if total_lines > 0 else 0,
            },
        },
    }


def save_high_freq_summary(
    template_list: List[Dict],
    cluster_to_lines: Dict[int, List[str]],
    output_dir: str,
    level_suffix: str,
    filename_prefix: Optional[str] = None,
    sample_count: int = 1,
) -> str:
    """
    Save sampled log lines for high-frequency error templates.

    Instead of dumping every line (which can be 10k+), this applies
    **per-template sampling**: for each template cluster, pick 7
    representative lines (first 3, middle 1, last 3) ordered by
    timestamp.  If a template has fewer than 7 lines, all lines are
    kept.

    Additionally, a companion **template file** is saved alongside the
    log-lines file.  It lists each template string with its cluster
    size, making it easy to see which patterns dominate.

    Args:
        template_list: List of high-frequency templates (sorted by size desc)
        cluster_to_lines: Mapping of cluster_id -> original lines
        output_dir: Output directory
        level_suffix: Level name (e.g., 'Error_HighFreq')
        filename_prefix: Optional filename prefix
        sample_count: Ignored (kept for backward compatibility)

    Returns:
        Path to the saved sampled-log-lines file
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    if filename_prefix:
        filename = output_path / f"{filename_prefix}_highfreq_error.txt"
        template_filename = output_path / f"{filename_prefix}_highfreq_error_templates.txt"
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = output_path / f"log_classification_highfreq_error_{timestamp}.txt"
        template_filename = output_path / f"log_classification_highfreq_error_templates_{timestamp}.txt"

    # ── Per-template sampling: first 3, middle 1, last 3 ──
    all_sampled_lines = []
    for tmpl in template_list:
        cid = tmpl['id']
        lines = cluster_to_lines.get(cid, [])
        if not lines:
            continue
        sampled = sample_lines_by_timestamp(lines, first_n=3, middle_n=1, last_n=3)
        all_sampled_lines.extend(sampled)

    # Write sampled log lines
    with open(filename, 'w', encoding='utf-8') as f:
        for line in all_sampled_lines:
            f.write(line + "\n")

    # ── Save companion template file ──
    with open(template_filename, 'w', encoding='utf-8') as f:
        f.write(f"# High-Frequency Error Templates ({len(template_list)} templates)\n")
        f.write(f"# Each template shown with cluster size (number of matching log lines)\n")
        f.write("=" * 80 + "\n\n")
        for i, tmpl in enumerate(template_list, 1):
            cid = tmpl['id']
            size = tmpl.get('size', len(cluster_to_lines.get(cid, [])))
            template_text = tmpl.get('template', '(unknown)')
            f.write(f"Template {i}  |  cluster_id={cid}  |  lines={size}\n")
            f.write(f"  {template_text}\n\n")

    return str(filename)


def save_rare_priority_templates(
    template_list: List[Dict],
    cluster_to_lines: Dict[int, List[str]],
    logs: List[Tuple[str, str]],
    event_ids: List,
    output_dir: str,
    level_suffix: str,
    filename_prefix: Optional[str] = None,
    max_original_lines_per_cluster: int = 5000,
) -> str:
    """
    Save only the log lines for rare/priority error templates (no templates/headers).
    These are the log lines from templates outside the Pareto threshold - priority for debugging.
    Also saves a companion template file listing each template with its cluster size.
    
    Args:
        template_list: List of rare templates (sorted by size desc)
        cluster_to_lines: Mapping of cluster_id -> original lines
        logs: List of (file_path, line) tuples (unused)
        event_ids: Event IDs from Drain3 (unused)
        output_dir: Output directory
        level_suffix: Level name (e.g., 'Error_Rare')
        filename_prefix: Optional filename prefix
        max_original_lines_per_cluster: Ignored
    
    Returns:
        Path to saved file
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    if filename_prefix:
        filename = output_path / f"{filename_prefix}_rare_error.txt"
        template_filename = output_path / f"{filename_prefix}_rare_error_templates.txt"
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = output_path / f"log_classification_rare_error_{timestamp}.txt"
        template_filename = output_path / f"log_classification_rare_error_templates_{timestamp}.txt"
    
    # Collect all log lines from all rare clusters
    all_lines = []
    for tmpl in template_list:
        cid = tmpl['id']
        lines = cluster_to_lines.get(cid, [])
        all_lines.extend(lines)
    
    # Write only the log lines
    with open(filename, 'w', encoding='utf-8') as f:
        for line in all_lines:
            f.write(line + "\n")

    # ── Save companion template file ──
    with open(template_filename, 'w', encoding='utf-8') as f:
        f.write(f"# Rare/Priority Error Templates ({len(template_list)} templates)\n")
        f.write(f"# Each template shown with cluster size (number of matching log lines)\n")
        f.write("=" * 80 + "\n\n")
        for i, tmpl in enumerate(template_list, 1):
            cid = tmpl['id']
            size = tmpl.get('size', len(cluster_to_lines.get(cid, [])))
            template_text = tmpl.get('template', '(unknown)')
            f.write(f"Template {i}  |  cluster_id={cid}  |  lines={size}\n")
            f.write(f"  {template_text}\n\n")
    
    return str(filename)


# =============================================================================
# MAIN PROCESSING FUNCTION
# =============================================================================
def process_log_file(
    file_path: str,
    config: Optional[PipelineConfig] = None,
    config_path: Optional[str] = None,
    **overrides
) -> Dict:
    """
    Main function to process a single log file.
    
    Configuration is loaded in the following priority:
        1. Explicit config object passed as parameter
        2. Config loaded from config_path JSON file
        3. Config loaded from log_config.json (auto-detected)
        4. Default configuration
    
    Override parameters (passed as **kwargs) can override config values:
        - output_dir: Output directory for template files
        - use_chunk_pipeline: Force branch selection (None=auto, True=chunk, False=entire)
        - parallel_chunks: For CHUNK pipeline: True = parallel, False = sequential
        - chunk_size: Lines per chunk
        - chunk_workers: Workers for parallel chunk processing
        - file_size_threshold_mb: Threshold for auto branch selection
    
    TWO BRANCHES:
        1. ENTIRE FILE: Loads entire file into memory, processes at once
        2. CHUNK: Reads file in chunks, processes each chunk
           - SEQUENTIAL: Chunks processed one at a time
           - PARALLEL: Chunks processed in parallel
    
    Returns:
        Dict with processing results:
            - file_path: Input file path
            - branch_used: 'ENTIRE_FILE' or 'CHUNK_SEQUENTIAL' or 'CHUNK_PARALLEL'
            - file_size_mb: File size in MB
            - elapsed_ms: Processing time
            - saved_files: Dict of level -> output file path
            - summary: Dict of level -> {count, templates_count, path}
            - config_used: Configuration file path or 'default'
            - error: Error message if failed
    """
    if not DRAIN3_AVAILABLE:
        return {
            "file_path": file_path,
            "error": "drain3 not installed. pip install drain3",
        }
    
    # Validate file exists
    if not Path(file_path).exists():
        return {
            "file_path": file_path,
            "error": f"File not found: {file_path}",
        }
    
    # Load configuration
    if config is not None:
        pass  # Use provided config
    elif config_path:
        config = load_config(config_path)
    else:
        config = get_config()
    
    # Apply overrides from kwargs
    if 'output_dir' in overrides and overrides['output_dir'] is not None:
        config.output_dir = overrides['output_dir']
    if 'use_chunk_pipeline' in overrides:
        config.use_chunk_pipeline = overrides['use_chunk_pipeline']
    if 'parallel_chunks' in overrides:
        config.parallel_chunks = overrides['parallel_chunks']
    if 'chunk_size' in overrides:
        config.chunk_size = overrides['chunk_size']
    if 'chunk_workers' in overrides:
        config.chunk_workers = overrides['chunk_workers']
    if 'file_size_threshold_mb' in overrides:
        config.file_size_threshold_mb = overrides['file_size_threshold_mb']
    
    # Set default output directory if not specified
    if config.output_dir is None:
        config.output_dir = str(Path(__file__).parent / "output")
    
    # Get file info
    try:
        file_size_mb = os.path.getsize(file_path) / (1024 * 1024)
    except:
        file_size_mb = 0
    
    # Determine which branch to use
    if config.use_chunk_pipeline is None:
        # Auto-select based on file size
        use_chunk = file_size_mb > config.file_size_threshold_mb
    else:
        use_chunk = config.use_chunk_pipeline
    
    # Determine branch name for reporting
    if use_chunk:
        branch_used = "CHUNK_PARALLEL" if config.parallel_chunks else "CHUNK_SEQUENTIAL"
    else:
        branch_used = "ENTIRE_FILE"
    
    level_names = {'E': 'Error', 'W': 'Warning', 'I': 'Information', 'UNKNOWN': 'Unknown'}
    stem = Path(file_path).stem or Path(file_path).name
    
    if config.print_progress:
        print(f"\n{'='*60}")
        print(f"Processing: {Path(file_path).name}")
        print(f"File size: {file_size_mb:.2f} MB")
        print(f"Branch: {branch_used}")
        if use_chunk:
            print(f"Chunk size: {config.chunk_size:,} lines")
            if config.parallel_chunks:
                workers = config.chunk_workers or f"auto (up to {min(multiprocessing.cpu_count(), 8)})"
                print(f"Chunk workers: {workers}")
        print(f"{'='*60}")
    
    # =========================================================================
    # STEP 1: Read and Categorize (based on branch)
    # =========================================================================
    start_time = time.perf_counter()
    
    try:
        if use_chunk:
            # BRANCH 2: CHUNK PIPELINE
            by_level = chunk_pipeline(file_path, config)
        else:
            # BRANCH 1: ENTIRE FILE PIPELINE
            by_level = entire_file_pipeline(file_path, config)
    except Exception as e:
        return {
            'file_path': file_path,
            'error': str(e),
            'branch_used': branch_used,
            'file_size_mb': file_size_mb,
        }
    
    categorize_time = time.perf_counter() - start_time
    
    if not by_level:
        return {
            'file_path': file_path,
            'error': None,
            'branch_used': branch_used,
            'file_size_mb': file_size_mb,
            'saved_files': {},
            'summary': {},
            'elapsed_ms': categorize_time * 1000,
        }
    
    # =========================================================================
    # STEP 2: Process with Drain3 (initial pass for all levels)
    # =========================================================================
    saved_files = {}
    summary = {}
    level_results = {}
    
    # First pass: Process all levels with Drain3
    for level in config.levels_to_process:
        level_data = by_level.get(level, {})
        # Support both new format {"preprocessed": [...], "original": [...]}
        # and old format (plain list)
        if isinstance(level_data, dict) and "preprocessed" in level_data:
            preprocessed_lines = level_data["preprocessed"]
            original_lines = level_data["original"]
        elif isinstance(level_data, list):
            preprocessed_lines = level_data
            original_lines = level_data  # fallback: no originals available
        else:
            continue
        if not preprocessed_lines:
            continue
        
        # Process with Drain3 using PREPROCESSED lines (timestamp-free, better clustering)
        cluster_sizes, template_list, event_ids = process_lines_with_drain3(
            preprocessed_lines, config
        )
        
        # Build cluster-to-lines mapping using ORIGINAL lines (with timestamps)
        # so output files contain the full original log lines
        cluster_to_lines = build_cluster_to_lines(original_lines, event_ids)
        
        level_results[level] = {
            'lines': original_lines,           # original lines for output
            'preprocessed_lines': preprocessed_lines,  # kept for internal use
            'template_list': template_list,
            'cluster_sizes': cluster_sizes,
            'event_ids': event_ids,
            'cluster_to_lines': cluster_to_lines,
        }
    
    # =========================================================================
    # STEP 3: Classify templates in W/I/U -> Error templates, Config templates, Regular
    #         (Working at TEMPLATE level - entire clusters move together)
    # =========================================================================
    classified_results = {}
    error_templates_to_merge = []  # Error templates found in W/I/U
    config_templates_to_merge = []  # Config templates found in W/I/U
    
    for level in ['W', 'I', 'UNKNOWN']:
        if level not in level_results:
            continue
        
        result = level_results[level]
        template_list = result['template_list']
        cluster_to_lines = result['cluster_to_lines']
        lines = result['lines']
        event_ids = result['event_ids']
        
        # Classify templates into error, config, regular
        classification = classify_templates_for_level(
            level, template_list, cluster_to_lines, lines, event_ids
        )
        
        classified_results[level] = classification
        
        # Collect error templates to merge into Error level
        if classification['error']['templates']:
            error_templates_to_merge.append({
                'source_level': level,
                **classification['error']
            })
            if config.print_progress:
                error_count = sum(len(v) for v in classification['error']['cluster_to_lines'].values())
                print(f"  [Shift->Error] {len(classification['error']['templates'])} templates ({error_count} lines) from {level_names.get(level, level)}")
        
        # Collect config templates
        if classification['config']['templates']:
            config_templates_to_merge.append({
                'source_level': level,
                **classification['config']
            })
            if config.print_progress:
                config_count = sum(len(v) for v in classification['config']['cluster_to_lines'].values())
                print(f"  [Shift->Config] {len(classification['config']['templates'])} templates ({config_count} lines) from {level_names.get(level, level)}")
        
        # Update level results with only regular templates
        regular = classification['regular']
        regular_lines, regular_event_ids = get_lines_for_clusters(
            lines, event_ids, regular['cluster_ids']
        )
        
        level_results[level] = {
            'lines': regular_lines,
            'template_list': regular['templates'],
            'cluster_sizes': {t['id']: t['size'] for t in regular['templates']},
            'event_ids': regular_event_ids,
            'cluster_to_lines': regular['cluster_to_lines'],
        }
    
    # =========================================================================
    # STEP 4: Merge error templates from W/I/U into Error level
    #         (Keep Drain3 templates - no re-processing needed)
    # =========================================================================
    if error_templates_to_merge:
        # Get existing Error level data
        existing_error = level_results.get('E', {
            'lines': [], 'template_list': [], 'cluster_sizes': {},
            'event_ids': [], 'cluster_to_lines': {}
        })
        
        # Merge error templates from W/I/U
        merged_error_templates = list(existing_error.get('template_list', []))
        merged_error_cluster_to_lines = dict(existing_error.get('cluster_to_lines', {}))
        merged_error_lines = list(existing_error.get('lines', []))
        merged_error_event_ids = list(existing_error.get('event_ids', []))
        
        for error_data in error_templates_to_merge:
            merged_error_templates.extend(error_data['templates'])
            merged_error_cluster_to_lines.update(error_data['cluster_to_lines'])
            # Get lines for these clusters from original data
            source_level = error_data['source_level']
            if source_level in classified_results:
                orig_lines = by_level.get(source_level, [])
                orig_result = level_results.get(source_level, {})
                # Add lines belonging to error clusters
                for cid, clines in error_data['cluster_to_lines'].items():
                    merged_error_lines.extend(clines)
                    merged_error_event_ids.extend([cid] * len(clines))
        
        level_results['E'] = {
            'lines': merged_error_lines,
            'template_list': merged_error_templates,
            'cluster_sizes': {t['id']: t['size'] for t in merged_error_templates},
            'event_ids': merged_error_event_ids,
            'cluster_to_lines': merged_error_cluster_to_lines,
        }
    
    # =========================================================================
    # STEP 5: Save templates for each level (filtered - without error/config templates)
    #         For Error level: apply Pareto/80-20 frequency classification
    # =========================================================================
    frequency_stats = {}  # Store frequency classification stats for return
    
    for level in config.levels_to_process:
        if level not in level_results:
            continue
        
        result = level_results[level]
        lines = result.get('lines', [])
        template_list = result.get('template_list', [])
        cluster_sizes = result.get('cluster_sizes', {})
        event_ids = result.get('event_ids', [])
        cluster_to_lines = result.get('cluster_to_lines', {})
        
        if not template_list:
            continue
        
        level_name = level_names.get(level, level)
        
        # Prepare logs tuple format for save_templates_to_file
        level_logs = [(file_path, line) for line in lines]
        
        # =====================================================================
        # SPECIAL HANDLING FOR ERROR LEVEL: Tiered Output (Pareto/80-20)
        # =====================================================================
        if level == 'E' and config.frequency.enable_tiered_error_output:
            # Classify error templates by frequency
            freq_classification = classify_templates_by_frequency(
                template_list, cluster_to_lines, config.frequency
            )
            
            high_freq = freq_classification['high_freq']
            rare = freq_classification['rare']
            
            # Store stats for return value
            frequency_stats['Error'] = {
                'high_freq': high_freq['stats'],
                'rare': rare['stats'],
                'threshold_pct': config.frequency.high_freq_cumulative_threshold * 100,
            }
            
            saved_error_paths = {}
            
            # Save HIGH-FREQUENCY templates (all lines included)
            if high_freq['templates']:
                high_freq_path = save_high_freq_summary(
                    high_freq['templates'],
                    high_freq['cluster_to_lines'],
                    config.output_dir,
                    level_name,
                    filename_prefix=stem,
                )
                saved_error_paths['high_freq'] = high_freq_path
                
                if config.print_progress:
                    pct = high_freq['stats']['line_coverage_pct']
                    print(f"  [highfreq_error] {high_freq['total_lines']:,} lines -> "
                          f"{len(high_freq['templates'])} templates ({pct:.1f}% coverage)")
            
            # Save RARE/PRIORITY templates (full detail)
            if rare['templates']:
                rare_logs = [(file_path, line) for cid in rare['cluster_ids'] 
                             for line in rare['cluster_to_lines'].get(cid, [])]
                rare_event_ids = [cid for cid in rare['cluster_ids'] 
                                  for _ in rare['cluster_to_lines'].get(cid, [])]
                
                rare_path = save_rare_priority_templates(
                    rare['templates'],
                    rare['cluster_to_lines'],
                    rare_logs,
                    rare_event_ids,
                    config.output_dir,
                    level_name,
                    filename_prefix=stem,
                )
                saved_error_paths['rare'] = rare_path
                
                if config.print_progress:
                    pct = rare['stats']['line_coverage_pct']
                    print(f"  [rare_error] {rare['total_lines']:,} lines -> "
                          f"{len(rare['templates'])} templates ({pct:.1f}% coverage)")
            
            # Also save combined Error file for backward compatibility
            saved_path = save_templates_to_file(
                template_list, cluster_sizes, level_logs, event_ids,
                config.output_dir, level_name, filename_prefix=stem,
                cluster_to_lines=cluster_to_lines,
            )
            saved_error_paths['combined'] = saved_path
            
            saved_files[level_name] = saved_error_paths
            summary[level_name] = {
                'count': len(lines),
                'templates_count': len(template_list),
                'paths': saved_error_paths,
                'frequency_classification': {
                    'high_freq_templates': len(high_freq['templates']),
                    'high_freq_lines': high_freq['total_lines'],
                    'rare_templates': len(rare['templates']),
                    'rare_lines': rare['total_lines'],
                    'threshold_pct': config.frequency.high_freq_cumulative_threshold * 100,
                },
            }
            
            if config.print_progress:
                print(f"  [Error] {len(lines):,} logs -> {len(template_list)} templates (combined)")
        
        else:
            # =====================================================================
            # STANDARD HANDLING FOR OTHER LEVELS (W, I, UNKNOWN)
            # =====================================================================
            # Save templates with all original lines
            saved_path = save_templates_to_file(
                template_list, cluster_sizes, level_logs, event_ids,
                config.output_dir, level_name, filename_prefix=stem,
                cluster_to_lines=cluster_to_lines,
            )
            
            saved_files[level_name] = saved_path
            summary[level_name] = {
                'count': len(lines),
                'templates_count': len(template_list),
                'path': saved_path,
            }
            
            if config.print_progress:
                print(f"  [{level_name}] {len(lines):,} logs -> {len(template_list)} templates")
    
    # =========================================================================
    # STEP 6: Save ConfigChanges templates (from W/I/U - keep Drain3 templates)
    # =========================================================================
    if config_templates_to_merge:
        # Merge all config templates (keeping Drain3 structure)
        merged_config = merge_template_results([
            {'templates': d['templates'], 'cluster_to_lines': d['cluster_to_lines'], 'cluster_ids': d['cluster_ids']}
            for d in config_templates_to_merge
        ])
        
        config_template_list = merged_config['templates']
        config_cluster_to_lines = merged_config['cluster_to_lines']
        
        # Get all config lines
        all_config_lines = []
        config_event_ids = []
        for cid, clines in config_cluster_to_lines.items():
            all_config_lines.extend(clines)
            config_event_ids.extend([cid] * len(clines))
        
        config_cluster_sizes = {t['id']: t['size'] for t in config_template_list}
        
        # Prepare logs tuple format
        config_logs = [(file_path, line) for line in all_config_lines]
        
        # Save config changes templates (all lines included)
        config_saved_path = save_templates_to_file(
            config_template_list, config_cluster_sizes, config_logs, config_event_ids,
            config.output_dir, "ConfigChanges", filename_prefix=stem,
            cluster_to_lines=config_cluster_to_lines,
        )
        
        saved_files['ConfigChanges'] = config_saved_path
        source_levels_list = [d['source_level'] for d in config_templates_to_merge]
        summary['ConfigChanges'] = {
            'count': len(all_config_lines),
            'templates_count': len(config_template_list),
            'path': config_saved_path,
            'source_levels': source_levels_list,
        }
        
        if config.print_progress:
            source_levels_str = ', '.join(level_names.get(l, l) for l in source_levels_list)
            print(f"  [ConfigChanges] {len(all_config_lines):,} logs -> {len(config_template_list)} templates (from {source_levels_str})")
    
    elapsed_ms = (time.perf_counter() - start_time) * 1000
    
    # Calculate stats for return value
    shifted_error_count = sum(
        sum(len(v) for v in d['cluster_to_lines'].values())
        for d in error_templates_to_merge
    ) if error_templates_to_merge else 0
    
    config_by_level = {
        level_names.get(d['source_level'], d['source_level']): sum(len(v) for v in d['cluster_to_lines'].values())
        for d in config_templates_to_merge
    } if config_templates_to_merge else {}
    
    if config.print_progress:
        print(f"\nCompleted in {elapsed_ms:.2f} ms")
        print(f"Output: {config.output_dir}")
        if shifted_error_count > 0:
            print(f"Note: {shifted_error_count} lines shifted from W/I/Unknown to Error")
        if frequency_stats:
            err_stats = frequency_stats.get('Error', {})
            if err_stats:
                hf = err_stats.get('high_freq', {})
                rare = err_stats.get('rare', {})
                print(f"Error frequency split: {hf.get('template_count', 0)} high-freq templates "
                      f"({hf.get('line_coverage_pct', 0):.1f}%), "
                      f"{rare.get('template_count', 0)} rare/priority templates "
                      f"({rare.get('line_coverage_pct', 0):.1f}%)")
    
    return {
        'file_path': file_path,
        'error': None,
        'branch_used': branch_used,
        'file_size_mb': file_size_mb,
        'elapsed_ms': elapsed_ms,
        'saved_files': saved_files,
        'summary': summary,
        'shifted_errors_count': shifted_error_count,
        'config_changes_by_level': config_by_level,
        'frequency_stats': frequency_stats,
    }


# =============================================================================
# AGENT INTERFACE - SINGLE POINT OF CONTACT
# =============================================================================

def analyze_logs(
    file_path: str,
    output_dir: Optional[str] = None,
    config_path: Optional[str] = None,
) -> Dict:
    """
    AGENT INTERFACE: Single point of contact for log analysis.
    
    All settings are controlled via log_config.json for consistent configuration.
    
    Args:
        file_path: Path to the log file to analyze
        output_dir: Output directory for generated files (None = use config)
        config_path: Path to config JSON file (None = auto-detect)
    
    Returns:
        Production-grade JSON response:
        {
            "status": "success" | "error",
            "error": null | "error message",
            "input": {
                "file": "/path/to/input.log",
                "size_mb": 12.5
            },
            "output_dir": "/path/to/output",
            "elapsed_ms": 1234.56,
            "files": {
                "rare_errors": {"path": "...", "templates": 45, "lines": 1500},
                "highfreq_errors": {"path": "...", "templates": 5, "lines": 8500},
                "warnings": {"path": "...", "templates": 12, "lines": 340},
                "information": {"path": "...", "templates": 8, "lines": 200},
                "unknown": {"path": "...", "templates": 3, "lines": 50},
                "config_changes": {"path": "...", "templates": 7, "lines": 120}
            },
            "totals": {
                "templates": 80,
                "lines": 10710
            },
            "error_analysis": {
                "pareto_threshold": 0.80,
                "highfreq": {"templates": 5, "lines": 8500, "coverage_pct": 85.0},
                "rare": {"templates": 45, "lines": 1500, "coverage_pct": 15.0}
            }
        }
    """
    # Input validation
    if not file_path:
        return {
            'status': 'error',
            'error': 'file_path is required',
            'input': {'file': None, 'size_mb': 0},
            'output_dir': None,
            'elapsed_ms': 0,
            'files': {},
            'totals': {'templates': 0, 'lines': 0},
            'error_analysis': None
        }
    
    file_path = str(Path(file_path).resolve())
    
    if not Path(file_path).exists():
        return {
            'status': 'error',
            'error': f'File not found: {file_path}',
            'input': {'file': file_path, 'size_mb': 0},
            'output_dir': None,
            'elapsed_ms': 0,
            'files': {},
            'totals': {'templates': 0, 'lines': 0},
            'error_analysis': None
        }
    
    if not DRAIN3_AVAILABLE:
        return {
            'status': 'error',
            'error': 'drain3 library not installed. Install with: pip install drain3',
            'input': {'file': file_path, 'size_mb': 0},
            'output_dir': None,
            'elapsed_ms': 0,
            'files': {},
            'totals': {'templates': 0, 'lines': 0},
            'error_analysis': None
        }
    
    # Load configuration (all flags come from config file)
    try:
        config = load_config(config_path)
    except Exception as e:
        return {
            'status': 'error',
            'error': f'Failed to load configuration: {str(e)}',
            'input': {'file': file_path, 'size_mb': 0},
            'output_dir': None,
            'elapsed_ms': 0,
            'files': {},
            'totals': {'templates': 0, 'lines': 0},
            'error_analysis': None
        }
    
    # Apply output directory override
    if output_dir:
        config.output_dir = output_dir
    
    # Get flags from config
    flags = config.output_flags
    include_rare_errors = flags.include_rare_errors
    include_highfreq_errors = flags.include_highfreq_errors
    include_warnings = flags.include_warnings
    include_information = flags.include_information
    include_unknown = flags.include_unknown
    include_config_changes = flags.include_config_changes
    
    # Determine which levels to process based on config flags
    levels_needed = set()
    if include_rare_errors or include_highfreq_errors:
        levels_needed.add('E')
    if include_warnings:
        levels_needed.add('W')
    if include_information:
        levels_needed.add('I')
    if include_unknown:
        levels_needed.add('UNKNOWN')
    if include_config_changes:
        levels_needed.update(['W', 'I', 'UNKNOWN'])
    
    config.levels_to_process = list(levels_needed) if levels_needed else ['E', 'W', 'I', 'UNKNOWN']
    config.frequency.enable_tiered_error_output = include_rare_errors or include_highfreq_errors
    
    # Run processing with error handling
    try:
        result = process_log_file(file_path, config=config)
    except Exception as e:
        return {
            'status': 'error',
            'error': f'Processing failed: {str(e)}',
            'input': {'file': file_path, 'size_mb': 0},
            'output_dir': config.output_dir,
            'elapsed_ms': 0,
            'files': {},
            'totals': {'templates': 0, 'lines': 0},
            'error_analysis': None
        }
    
    # Error response from process_log_file
    if result.get('error'):
        return {
            'status': 'error',
            'error': result['error'],
            'input': {'file': file_path, 'size_mb': result.get('file_size_mb', 0)},
            'output_dir': config.output_dir,
            'elapsed_ms': result.get('elapsed_ms', 0),
            'files': {},
            'totals': {'templates': 0, 'lines': 0},
            'error_analysis': None
        }
    
    # Build file outputs
    files = {}
    total_templates = 0
    total_lines = 0
    
    saved_files = result.get('saved_files', {})
    summary = result.get('summary', {})
    
    # Error outputs (tiered)
    error_data = saved_files.get('Error', {})
    error_summary = summary.get('Error', {})
    freq_class = error_summary.get('frequency_classification', {}) if isinstance(error_summary, dict) else {}
    
    if isinstance(error_data, dict):
        if include_rare_errors and 'rare' in error_data:
            t_count = freq_class.get('rare_templates', 0)
            l_count = freq_class.get('rare_lines', 0)
            files['rare_errors'] = {'path': error_data['rare'], 'templates': t_count, 'lines': l_count}
            total_templates += t_count
            total_lines += l_count
        
        if include_highfreq_errors and 'high_freq' in error_data:
            t_count = freq_class.get('high_freq_templates', 0)
            l_count = freq_class.get('high_freq_lines', 0)
            files['highfreq_errors'] = {'path': error_data['high_freq'], 'templates': t_count, 'lines': l_count}
            total_templates += t_count
            total_lines += l_count
    elif isinstance(error_data, str) and (include_rare_errors or include_highfreq_errors):
        t_count = error_summary.get('templates_count', 0)
        l_count = error_summary.get('count', 0)
        files['errors'] = {'path': error_data, 'templates': t_count, 'lines': l_count}
        total_templates += t_count
        total_lines += l_count
    
    # Warning output
    if include_warnings and 'Warning' in saved_files:
        s = summary.get('Warning', {})
        t_count, l_count = s.get('templates_count', 0), s.get('count', 0)
        files['warnings'] = {'path': saved_files['Warning'], 'templates': t_count, 'lines': l_count}
        total_templates += t_count
        total_lines += l_count
    
    # Information output
    if include_information and 'Information' in saved_files:
        s = summary.get('Information', {})
        t_count, l_count = s.get('templates_count', 0), s.get('count', 0)
        files['information'] = {'path': saved_files['Information'], 'templates': t_count, 'lines': l_count}
        total_templates += t_count
        total_lines += l_count
    
    # Unknown output
    if include_unknown and 'Unknown' in saved_files:
        s = summary.get('Unknown', {})
        t_count, l_count = s.get('templates_count', 0), s.get('count', 0)
        files['unknown'] = {'path': saved_files['Unknown'], 'templates': t_count, 'lines': l_count}
        total_templates += t_count
        total_lines += l_count
    
    # ConfigChanges output
    if include_config_changes and 'ConfigChanges' in saved_files:
        s = summary.get('ConfigChanges', {})
        t_count, l_count = s.get('templates_count', 0), s.get('count', 0)
        files['config_changes'] = {'path': saved_files['ConfigChanges'], 'templates': t_count, 'lines': l_count}
        total_templates += t_count
        total_lines += l_count
    
    # Error analysis (Pareto stats)
    error_analysis = None
    freq_stats = result.get('frequency_stats', {}).get('Error', {})
    if freq_stats:
        hf = freq_stats.get('high_freq', {})
        rare = freq_stats.get('rare', {})
        error_analysis = {
            'pareto_threshold': config.frequency.high_freq_cumulative_threshold,
            'highfreq': {
                'templates': hf.get('template_count', 0),
                'lines': freq_class.get('high_freq_lines', 0),
                'coverage_pct': round(hf.get('line_coverage_pct', 0), 1)
            },
            'rare': {
                'templates': rare.get('template_count', 0),
                'lines': freq_class.get('rare_lines', 0),
                'coverage_pct': round(rare.get('line_coverage_pct', 0), 1)
            }
        }
    
    return {
        'status': 'success',
        'error': None,
        'input': {
            'file': file_path,
            'size_mb': round(result.get('file_size_mb', 0), 2)
        },
        'output_dir': config.output_dir,
        'elapsed_ms': round(result.get('elapsed_ms', 0), 2),
        'files': files,
        'totals': {
            'templates': total_templates,
            'lines': total_lines
        },
        'error_analysis': error_analysis
    }


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================
def get_file_info(file_path: str) -> Dict:
    """Get file size and line count info."""
    try:
        size_bytes = os.path.getsize(file_path)
        size_mb = size_bytes / (1024 * 1024)
        
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            line_count = sum(1 for _ in f)
        
        return {
            'path': file_path,
            'name': Path(file_path).name,
            'size_mb': size_mb,
            'line_count': line_count,
        }
    except Exception as e:
        return {
            'path': file_path,
            'name': Path(file_path).name,
            'size_mb': 0,
            'line_count': 0,
            'error': str(e),
        }


def compare_branches(file_path: str, output_base: str = None) -> Dict:
    """
    Compare all three processing modes on the same file.
    
    Runs:
        1. ENTIRE_FILE branch
        2. CHUNK_SEQUENTIAL branch
        3. CHUNK_PARALLEL branch
    
    Returns comparison results with timing for each.
    """
    if output_base is None:
        output_base = str(Path(__file__).parent / "comparison_output")
    
    file_info = get_file_info(file_path)
    print(f"\n{'='*80}")
    print(f"BRANCH COMPARISON: {file_info['name']}")
    print(f"Size: {file_info['size_mb']:.2f} MB, Lines: {file_info.get('line_count', 'N/A'):,}")
    print(f"{'='*80}")
    
    results = {}
    
    # 1. ENTIRE FILE branch
    print("\n[1/3] Running ENTIRE_FILE branch...")
    results['entire_file'] = process_log_file(
        file_path,
        output_dir=f"{output_base}/entire_file",
        use_chunk_pipeline=False,
    )
    
    # 2. CHUNK SEQUENTIAL branch
    print("\n[2/3] Running CHUNK_SEQUENTIAL branch...")
    results['chunk_sequential'] = process_log_file(
        file_path,
        output_dir=f"{output_base}/chunk_sequential",
        use_chunk_pipeline=True,
        parallel_chunks=False,
    )
    
    # 3. CHUNK PARALLEL branch
    print("\n[3/3] Running CHUNK_PARALLEL branch...")
    results['chunk_parallel'] = process_log_file(
        file_path,
        output_dir=f"{output_base}/chunk_parallel",
        use_chunk_pipeline=True,
        parallel_chunks=True,
    )
    
    # Print comparison
    print(f"\n{'='*80}")
    print("TIMING COMPARISON")
    print(f"{'='*80}")
    
    for name, result in results.items():
        elapsed = result.get('elapsed_ms', 0)
        branch = result.get('branch_used', 'N/A')
        print(f"  {name:20s}: {elapsed:>10.2f} ms ({branch})")
    
    # Find fastest
    times = {k: v.get('elapsed_ms', float('inf')) for k, v in results.items()}
    fastest = min(times, key=times.get)
    print(f"\n  FASTEST: {fastest} ({times[fastest]:.2f} ms)")
    
    return {
        'file_info': file_info,
        'results': results,
        'fastest': fastest,
    }


# =============================================================================
# MAIN
# =============================================================================
def main():
    """
    Main function demonstrating the pipeline.
    
    Usage:
        python testing-log.py                             # Use default test file with analyze_logs
        python testing-log.py file.log                    # Process single file with analyze_logs
        python testing-log.py file.log --analyze          # Use analyze_logs (default, explicit)
        python testing-log.py file.log --legacy           # Use legacy process_log_file
        python testing-log.py file.log --compare          # Compare all branches
        python testing-log.py file.log --config path      # Use specific config file
        python testing-log.py file.log --output dir       # Specify output directory
        python testing-log.py file.log --chunk            # Force chunk pipeline (legacy mode)
        python testing-log.py file.log --entire           # Force entire file pipeline (legacy mode)
        python testing-log.py file.log --sequential       # Force sequential chunk processing (legacy mode)
    """
    import sys
    import json as json_module
    
    script_dir = Path(__file__).parent
    
    # Parse arguments
    args = sys.argv[1:]
    
    # Parse flags
    analyze_mode = '--analyze' in args or '--legacy' not in args  # Default to analyze mode
    legacy_mode = '--legacy' in args
    compare_mode = '--compare' in args
    force_chunk = '--chunk' in args
    force_entire = '--entire' in args
    force_sequential = '--sequential' in args
    
    # Parse --config and --output options
    config_path = None
    output_dir = None
    
    filtered_args = []
    i = 0
    while i < len(args):
        if args[i] == '--config' and i + 1 < len(args):
            config_path = args[i + 1]
            i += 2
        elif args[i] == '--output' and i + 1 < len(args):
            output_dir = args[i + 1]
            i += 2
        elif args[i] not in ['--compare', '--chunk', '--entire', '--sequential', '--analyze', '--legacy']:
            filtered_args.append(args[i])
            i += 1
        else:
            i += 1
    
    args = filtered_args
    
    # Get file path
    if args:
        file_path = str(Path(args[0]).resolve())
    else:
        # Default test files
        default_files = [
            script_dir / "current.log",
            script_dir / 'crio_service.log',
            script_dir / "kubelet_service.log",
        ]
        for f in default_files:
            if f.exists():
                file_path = str(f)
                break
        else:
            print("Error: No log file found.")
            print("\nUsage: python testing-log.py <file.log> [OPTIONS]")
            print("\nOptions:")
            print("  --analyze          Use analyze_logs function (default)")
            print("  --legacy           Use legacy process_log_file function")
            print("  --config <path>    Use specific config file")
            print("  --output <dir>     Specify output directory")
            print("  --compare          Compare all branches (legacy mode)")
            print("  --chunk            Force chunk pipeline (legacy mode)")
            print("  --entire           Force entire file pipeline (legacy mode)")
            print("  --sequential       Force sequential chunk processing (legacy mode)")
            sys.exit(1)
    
    # Validate file exists
    if not Path(file_path).exists():
        print(f"Error: File not found: {file_path}")
        sys.exit(1)
    
    # Check drain3
    if not DRAIN3_AVAILABLE:
        print("Error: drain3 is not installed. Install with: pip install drain3")
        sys.exit(1)
    
    # =========================================================================
    # MODE: analyze_logs (NEW - default)
    # =========================================================================
    if analyze_mode and not legacy_mode and not compare_mode:
        print("\n" + "=" * 60)
        print("ANALYZE LOGS MODE (Agent Interface)")
        print("=" * 60)
        print(f"File: {file_path}")
        print(f"Config: {config_path or 'auto-detect'}")
        print(f"Output: {output_dir or 'auto'}")
        print("=" * 60 + "\n")
        
        # Call analyze_logs
        result = analyze_logs(
            file_path=file_path,
            output_dir=output_dir,
            config_path=config_path,
        )
        
        # Print JSON result
        print("\n" + "=" * 60)
        print("JSON RESPONSE")
        print("=" * 60)
        print(json_module.dumps(result, indent=2))
        print("=" * 60)
        
        if result['status'] == 'error':
            sys.exit(1)
    
    # =========================================================================
    # MODE: Legacy (process_log_file)
    # =========================================================================
    else:
        # Load config (will auto-detect log_config.json if config_path not specified)
        config = load_config(config_path)
        
        # Apply command-line overrides
        overrides = {}
        if output_dir:
            overrides['output_dir'] = output_dir
        if force_chunk:
            overrides['use_chunk_pipeline'] = True
        if force_entire:
            overrides['use_chunk_pipeline'] = False
        if force_sequential:
            overrides['parallel_chunks'] = False
        
        if compare_mode:
            # Compare all branches
            compare_branches(file_path)
        else:
            # Process with config
            result = process_log_file(file_path, config=config, **overrides)
            if result.get('error'):
                print(f"Error: {result['error']}")
                sys.exit(1)


if __name__ == "__main__":
    main()